services:
  backend:
    build:
      context: ./backend
      target: prod
    environment:
      - ENV=production
    volumes: []

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes: []
